# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
AvailableService.create!([
  {user_id: -1, service_description: "Software Setup (Includes Import)", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Setup Accounts", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Setup Financial Statements", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Software Training", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Bookkeeping Software (2 Users)", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Software Support", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Bookkeeping Software Tuneup", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Online Bookkeeping Software", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Online Software Support", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Financial Statement Preparation", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Bank Reconciliation", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Credit Card Reconciliation", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Payroll", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Data Collection & Delivery", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Engagement Letters", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Dedicated Account Manager", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Communication During Business Hours", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "After Hours Communication", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Business Financial Coaching Sessions", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Year-End Tax Planning", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Tax Preparation", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Monthly Bookkeeping", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Quartley Bookkeeping", service_type: 1, custom_service: 0},
  {user_id: -1, service_description: "Annual Bookkeeping ", service_type: 1, custom_service: 0},
  ])

BusinessType.create!([
  {industry_code: "0000", description: "All Industries                          "},
  {industry_code: "0700", description: "Agricultural Services                   "},
  {industry_code: "0710", description: "Agricultural Services - MISC            "},
  {industry_code: "0711", description: "Farming                                 "},
  {industry_code: "0742", description: "Veterinarians                           "},
  {industry_code: "0752", description: "Pet Washing and Grooming                "},
  {industry_code: "0753", description: "Kennels                                 "},
  {industry_code: "8900", description: "National Accounts"},
  {industry_code: "0782", description: "Lawn Maintenance                        "},
  {industry_code: "0783", description: "Tree Service                            "},
  {industry_code: "0800", description: "Resources                               "},
  {industry_code: "0810", description: "Resources-MISC                          "},
  {industry_code: "1500", description: "Contractors                             "},
  {industry_code: "1510", description: "Contractors-MISC                        "},
  {industry_code: "1511", description: "General Contractors                     "},
  {industry_code: "1512", description: "Sheet Metal Contractors                 "},
  {industry_code: "1513", description: "Plumbing Contractors                    "},
  {industry_code: "1514", description: "Septic Tanks Contractors                "},
  {industry_code: "1515", description: "Heating & A/C Contractors               "},
  {industry_code: "1516", description: "Paving Contractors                      "},
  {industry_code: "1522", description: "Painting Contractors                    "},
  {industry_code: "1523", description: "Sewer Contractors                       "},
  {industry_code: "1531", description: "Electrical Contractors                  "},
  {industry_code: "1532", description: "Carpenters / Cabinet Makers             "},
  {industry_code: "1541", description: "Masonry Contractors                     "},
  {industry_code: "1543", description: "Tile & Ceramic Contractors              "},
  {industry_code: "1561", description: "Roofing Contractors                     "},
  {industry_code: "1562", description: "Siding Contractors                      "},
  {industry_code: "1571", description: "Concrete Contractors                    "},
  {industry_code: "1581", description: "Landscape Contractors                   "},
  {industry_code: "1594", description: "Excavating Contractors                  "},
  {industry_code: "2700", description: "Printing and Publishing                 "},
  {industry_code: "2710", description: "Printing/Publishing-MISC                "},
  {industry_code: "2711", description: "Newspapers                              "},
  {industry_code: "2752", description: "Printers & Typesetting                  "},
  {industry_code: "3900", description: "General Manufacturing                   "},
  {industry_code: "3910", description: "Manufacturing-MISC                      "},
  {industry_code: "3992", description: "Sign Manufacturing                      "},
  {industry_code: "4200", description: "Transportation                          "},
  {industry_code: "4210", description: "Transportation-MISC                     "},
  {industry_code: "4212", description: "Delivery Service                        "},
  {industry_code: "4213", description: "Trucking                                "},
  {industry_code: "4214", description: "Movers                                  "},
  {industry_code: "4219", description: "Limo & Taxicab Services                 "},
  {industry_code: "4225", description: "Storage                                 "},
  {industry_code: "4235", description: "Water Transportation                    "},
  {industry_code: "4245", description: "Travel Agencies                         "},
  {industry_code: "4900", description: "Utilities                               "},
  {industry_code: "4910", description: "Utilities-MISC                          "},
  {industry_code: "4920", description: "Communications                          "},
  {industry_code: "4953", description: "Garbage Collection                      "},
  {industry_code: "5000", description: "Wholesale                               "},
  {industry_code: "5010", description: "Wholesale-MISC                          "},
  {industry_code: "5099", description: "Manufacturing Representative            "},
  {industry_code: "5200", description: "Building Materials-Retail               "},
  {industry_code: "5210", description: "Building Materials-MISC                 "},
  {industry_code: "5211", description: "Windows & Doors - Retail                "},
  {industry_code: "5212", description: "Plumbing Fixtures - Retail              "},
  {industry_code: "5213", description: "Building Materials - Retail             "},
  {industry_code: "5231", description: "Wall coverings - Retail                 "},
  {industry_code: "5232", description: "Paint - Retail                          "},
  {industry_code: "5233", description: "Glass - Retail                          "},
  {industry_code: "5252", description: "Hardware - Retail                       "},
  {industry_code: "5261", description: "Lawn & Garden Equip - Retail            "},
  {industry_code: "5300", description: "General Merchandise                     "},
  {industry_code: "5310", description: "General Merchandise-MISC                "},
  {industry_code: "5311", description: "Department Stores                       "},
  {industry_code: "5331", description: "Variety Stores                          "},
  {industry_code: "5400", description: "Food Stores                             "},
  {industry_code: "5410", description: "Food Stores-MISC                        "},
  {industry_code: "5411", description: "Food Markets                            "},
  {industry_code: "5412", description: "Convenience Stores                      "},
  {industry_code: "5413", description: "Vending - Food                          "},
  {industry_code: "5421", description: "Meat & Seafood - Retail                 "},
  {industry_code: "5431", description: "Fruits & Vegetables - Retail            "},
  {industry_code: "5441", description: "Candy & Confectionery - Retail          "},
  {industry_code: "5471", description: "Bagel Shops                             "},
  {industry_code: "5461", description: "Bakers - Retail                         "},
  {industry_code: "5499", description: "Health Food - Retail                    "},
  {industry_code: "5500", description: "Vehicle & Fuel                          "},
  {industry_code: "5510", description: "Vehicle & Fuel-MISC                     "},
  {industry_code: "5511", description: "Auto Dealers - New Cars                 "},
  {industry_code: "5512", description: "Auto Dealers - Used Cars                "},
  {industry_code: "5532", description: "Auto Parts Supply - New                 "},
  {industry_code: "5533", description: "Tire Dealers                            "},
  {industry_code: "5534", description: "Auto Security & Alarm Dealers           "},
  {industry_code: "5535", description: "Auto Radio & Stereo Dealers             "},
  {industry_code: "5571", description: "Mototcycle & ATV Dealers                "},
  {industry_code: "5541", description: "Service Stations                        "},
  {industry_code: "5551", description: "Boat Dealers                            "},
  {industry_code: "5572", description: "Golf Cart Dealers                       "},
  {industry_code: "5600", description: "Apparel/Accessory Stores                "},
  {industry_code: "5610", description: "Apparel/Accessory-MISC                  "},
  {industry_code: "5611", description: "Clothing - Men's Store                  "},
  {industry_code: "5621", description: "Clothing - Women's Store                "},
  {industry_code: "5623", description: "Bridal Shops                            "},
  {industry_code: "5641", description: "Clothing - Children's Store             "},
  {industry_code: "5661", description: "Shoe Store                              "},
  {industry_code: "5691", description: "Sportswear Store                        "},
  {industry_code: "5697", description: "Tailor                                  "},
  {industry_code: "5698", description: "T-Shirts - Retail                       "},
  {industry_code: "5700", description: "Furniture/Furnishing                    "},
  {industry_code: "5723", description: "Vacuum Cleaner/Sewing Machine Dealers   "},
  {industry_code: "5710", description: "Furniture/Furnishing-MISC               "},
  {industry_code: "5713", description: "Furniture Dealers - Retail              "},
  {industry_code: "5714", description: "Floor Materials - Retail                "},
  {industry_code: "5716", description: "Draperies & Curtains - Retail           "},
  {industry_code: "5722", description: "Appliances- Retail                      "},
  {industry_code: "5733", description: "Electronic Equipment - Retail           "},
  {industry_code: "5734", description: "Computer - Retail                       "},
  {industry_code: "5736", description: "Records, Tapes, CD - Retail             "},
  {industry_code: "5738", description: "Video Tape Sales - Retail               "},
  {industry_code: "5800", description: "Eating and Drinking                     "},
  {industry_code: "5810", description: "Eating and Drinking-MISC                "},
  {industry_code: "5812", description: "Ice Cream Parlors                       "},
  {industry_code: "5813", description: "Food - Carry Out                        "},
  {industry_code: "5814", description: "Restaurants                             "},
  {industry_code: "5815", description: "Delicatessens                           "},
  {industry_code: "5816", description: "Caterers                                "},
  {industry_code: "5817", description: "Sandwich Shops                          "},
  {industry_code: "5818", description: "Pizza Shops                             "},
  {industry_code: "5819", description: "Bars, Night Clubs, Lounges              "},
  {industry_code: "5820", description: "Coffee & Donut Shops                    "},
  {industry_code: "5912", description: "Pharmacies                              "},
  {industry_code: "5900", description: "General Retail                          "},
  {industry_code: "5910", description: "General Retail-MISC                     "},
  {industry_code: "5921", description: "Liquors - Retail                        "},
  {industry_code: "5924", description: "Consignment Shops                       "},
  {industry_code: "5938", description: "Golf Equipment & Supplies               "},
  {industry_code: "5925", description: "Second Hand/Thrift Shops                "},
  {industry_code: "5932", description: "Antiques Dealers                        "},
  {industry_code: "5933", description: "Music Shops                             "},
  {industry_code: "5939", description: "Bicycle Dealers                         "},
  {industry_code: "5941", description: "Sporting Goods - Retail                 "},
  {industry_code: "5942", description: "Guns & Gunsmiths - Retail               "},
  {industry_code: "5944", description: "Book Dealers - Retail                   "},
  {industry_code: "5945", description: "Office Supplies - Retail                "},
  {industry_code: "5946", description: "Jewelry - Retail                        "},
  {industry_code: "5949", description: "Greeting Cards - Retail                 "},
  {industry_code: "5947", description: "Craft Supplies - Retail                 "},
  {industry_code: "5948", description: "Balloon & Toys - Retail                 "},
  {industry_code: "5950", description: "Gift Shops - Retail                     "},
  {industry_code: "5951", description: "Fabric Shops - Retail                   "},
  {industry_code: "5980", description: "Picture Frame Dealers                   "},
  {industry_code: "5982", description: "Pet Shops                               "},
  {industry_code: "5983", description: "Wedding Supplies/Services               "},
  {industry_code: "5984", description: "Art Galleries and Dealers               "},
  {industry_code: "5985", description: "Cosmetics/Perfumes - Retail             "},
  {industry_code: "5986", description: "Cigar, Cigarette, Tobacco - Retail      "},
  {industry_code: "5992", description: "Florists - Retail                       "},
  {industry_code: "5994", description: "Trophy Shops                            "},
  {industry_code: "5995", description: "Optical Goods - Retail                  "},
  {industry_code: "5996", description: "Hearing Aids- Retail                    "},
  {industry_code: "5998", description: "Telephone Equipment - Retail            "},
  {industry_code: "5999", description: "Sports Cards & Memorabilia              "},
  {industry_code: "6400", description: "Insurance                               "},
  {industry_code: "6410", description: "Insurance-MISC                          "},
  {industry_code: "6420", description: "Insurance Brokers                       "},
  {industry_code: "6500", description: "Real Estate                             "},
  {industry_code: "6510", description: "Real Estate  - MISC                     "},
  {industry_code: "6513", description: "Real Estate - Condominiums              "},
  {industry_code: "6514", description: "Real Estate - Apartments                "},
  {industry_code: "6515", description: "Mobile Home Parks                       "},
  {industry_code: "6531", description: "Real Estate Management                  "},
  {industry_code: "6532", description: "Real Estate Appraisers                  "},
  {industry_code: "7012", description: "Resorts                                 "},
  {industry_code: "6552", description: "Real Estate Brokers                     "},
  {industry_code: "6600", description: "Financial Services                      "},
  {industry_code: "6610", description: "Financial Services-MISC                 "},
  {industry_code: "6611", description: "Pawn Shops                              "},
  {industry_code: "7000", description: "Hotels/Camps/Lodging                    "},
  {industry_code: "7010", description: "Hotels/Camps/Lodging-MISC               "},
  {industry_code: "7011", description: "Motels & Hotels                         "},
  {industry_code: "7033", description: "Campgrounds                             "},
  {industry_code: "7200", description: "Personal Services                       "},
  {industry_code: "7215", description: "Laundries - Self Serve                  "},
  {industry_code: "7210", description: "Personal Services-MISC                  "},
  {industry_code: "7211", description: "Laundries & Dry Cleaners                "},
  {industry_code: "7212", description: "Cleaning Services                       "},
  {industry_code: "7216", description: "Pool Services                           "},
  {industry_code: "7294", description: "Formal Wear Rental                      "},
  {industry_code: "7217", description: "Carpet and Rug Cleaners                 "},
  {industry_code: "7221", description: "Photographers - Portrait                "},
  {industry_code: "7231", description: "Manicuring                              "},
  {industry_code: "7232", description: "Beauty Salons                           "},
  {industry_code: "7241", description: "Barber Shops                            "},
  {industry_code: "7261", description: "Funeral Directors                       "},
  {industry_code: "7251", description: "Shoe Repair                             "},
  {industry_code: "7295", description: "Tatoo Parlors                           "},
  {industry_code: "7298", description: "Weight Control Services                 "},
  {industry_code: "7299", description: "Tanning Salons                          "},
  {industry_code: "7300", description: "Business Services                       "},
  {industry_code: "7310", description: "Business Services-MISC                  "},
  {industry_code: "7311", description: "Advertising Agencies                    "},
  {industry_code: "7334", description: "Copying/Duplicating Services            "},
  {industry_code: "7335", description: "Photographers- Commercial               "},
  {industry_code: "7336", description: "Graphic Designers                       "},
  {industry_code: "7338", description: "Secretarial Services                    "},
  {industry_code: "7340", description: "Mail Boxes                              "},
  {industry_code: "7342", description: "Pest Control                            "},
  {industry_code: "7349", description: "Janitorial Services                     "},
  {industry_code: "7359", description: "Equipment Rental                        "},
  {industry_code: "7361", description: "Employment Agencies                     "},
  {industry_code: "7371", description: "Computer Consultants                    "},
  {industry_code: "7378", description: "Computer Repair                         "},
  {industry_code: "7384", description: "Photo Finishing - Retail                "},
  {industry_code: "7389", description: "Auctioneers                             "},
  {industry_code: "7390", description: "Interior Decorators                     "},
  {industry_code: "7391", description: "Appraisers                              "},
  {industry_code: "7392", description: "Notaries Public                         "},
  {industry_code: "7500", description: "Auto Repair & Garages                   "},
  {industry_code: "7513", description: "Truck Renting and Leasing               "},
  {industry_code: "7510", description: "Auto Repair & Garages-MISC              "},
  {industry_code: "7514", description: "Auto Renting and Leasing                "},
  {industry_code: "7519", description: "Trailer Renting and Leasing             "},
  {industry_code: "7532", description: "Auto Body Repair/Painting               "},
  {industry_code: "7533", description: "Muffler Repair                          "},
  {industry_code: "7534", description: "Customizing - Auto                      "},
  {industry_code: "7536", description: "Window Tinting - Auto                   "},
  {industry_code: "7537", description: "Transmission Auto                       "},
  {industry_code: "7538", description: "Auto Repair                             "},
  {industry_code: "7539", description: "Truck Repair                            "},
  {industry_code: "7540", description: "Radiator Repair - Auto                  "},
  {industry_code: "7541", description: "Alignment and Frame - Auto              "},
  {industry_code: "7542", description: "Brake Service                           "},
  {industry_code: "7543", description: "Car Washing & Polishing                 "},
  {industry_code: "7549", description: "Wrecker Service                         "},
  {industry_code: "7624", description: "Air Conditioning Repair                 "},
  {industry_code: "7600", description: "Repair Services                         "},
  {industry_code: "7610", description: "Repair Services-MISC                    "},
  {industry_code: "7622", description: "Electronics Repair                      "},
  {industry_code: "7629", description: "Appliance - Repair                      "},
  {industry_code: "7631", description: "Jewelry Repair                          "},
  {industry_code: "7641", description: "Upholsterers                            "},
  {industry_code: "7651", description: "Machine Shops                           "},
  {industry_code: "7692", description: "Welding                                 "},
  {industry_code: "7697", description: "Taxidermists                            "},
  {industry_code: "7698", description: "Drain and Sewer Cleaning                "},
  {industry_code: "7699", description: "Locks and Locksmiths                    "},
  {industry_code: "7800", description: "Motion Pictures                         "},
  {industry_code: "7810", description: "Motion Pictures-MISC                    "},
  {industry_code: "7812", description: "Video Production Services               "},
  {industry_code: "7841", description: "Video Tape Rental                       "},
  {industry_code: "7900", description: "Amusement and Recreation                "},
  {industry_code: "7910", description: "Amusement and Recreation-MISC           "},
  {industry_code: "7911", description: "Dancing Instruction                     "},
  {industry_code: "7922", description: "Talent Agency                           "},
  {industry_code: "7991", description: "Health Club                             "},
  {industry_code: "7999", description: "Martial Arts Instruction                "},
  {industry_code: "8000", description: "Medical & Health                        "},
  {industry_code: "8010", description: "Medical & Health-MISC                   "},
  {industry_code: "8011", description: "Physicians & Surgeons                   "},
  {industry_code: "8012", description: "Medical Clinics                         "},
  {industry_code: "8021", description: "Dentists                                "},
  {industry_code: "8041", description: "Chiropractors DC                        "},
  {industry_code: "8042", description: "Optometrists OD                         "},
  {industry_code: "8043", description: "Podiatrists                             "},
  {industry_code: "8049", description: "Nurses and Nurse Registry               "},
  {industry_code: "8050", description: "Physical Therapists                     "},
  {industry_code: "8051", description: "Psychologists                           "},
  {industry_code: "8052", description: "Nursing Homes                           "},
  {industry_code: "8059", description: "Retirement Homes                        "},
  {industry_code: "8072", description: "Laboratories                            "},
  {industry_code: "8082", description: "Home Health Services                    "},
  {industry_code: "8100", description: "Legal Services                          "},
  {industry_code: "8110", description: "Legal Services-MISC                     "},
  {industry_code: "8111", description: "Attorneys                               "},
  {industry_code: "8200", description: "Educational Services                    "},
  {industry_code: "8310", description: "Social Services-MISC                    "},
  {industry_code: "8210", description: "Educational Services-MISC               "},
  {industry_code: "8300", description: "Social Services                         "},
  {industry_code: "8322", description: "Marriage/Family Counsellors             "},
  {industry_code: "8351", description: "Child Care Services                     "},
  {industry_code: "8352", description: "Nursery School                          "},
  {industry_code: "8600", description: "Membership Organizations                "},
  {industry_code: "8610", description: "Membership Org.-MISC                    "},
  {industry_code: "8700", description: "Engineers/Consultants                   "},
  {industry_code: "8710", description: "Engineers/Consultants-MISC              "},
  {industry_code: "8711", description: "Engineers                               "},
  {industry_code: "8712", description: "Architects                              "},
  {industry_code: "8713", description: "Surveyors - Land                        "},
  {industry_code: "8721", description: "Accountants                             "},
  {industry_code: "8742", description: "Business Consultants                    "},
  {industry_code: "9000", description: "Test & Internal Use                     "},
  {industry_code: "9010", description: "Sample Chart of Accounts                "},
  {industry_code: "9020", description: "Test Clients                            "},
  {industry_code: "9030", description: "Accountants - Padgett                   "},
  {industry_code: "8910", description: "National Accounts-MISC"},
  {industry_code: "8911", description: "PostNet"}
])

